// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Context;

<<<<<<< HEAD
<<<<<<< HEAD
#nullable disable

=======
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
namespace dotnetapp.Migrations
{
    [DbContext(typeof(PostPaidDbContext))]
    partial class PostPaidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
<<<<<<< HEAD
<<<<<<< HEAD
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);
=======
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

            modelBuilder.Entity("dotnetapp.Models.Addons", b =>
                {
                    b.Property<int>("addonId")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addonId"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("addonDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addonPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addonId");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("Addons", (string)null);
=======
                    b.ToTable("Addons");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("Addons");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("admins", (string)null);
=======
                    b.ToTable("admins");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("admins");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("logins", (string)null);
=======
                    b.ToTable("logins");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("logins");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.PostPaid", b =>
                {
                    b.Property<int>("planId")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("planId"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("planDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planOffers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("planValidity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("planId");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("PostPaid", (string)null);
=======
                    b.ToTable("PostPaid");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("PostPaid");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.Recharge", b =>
                {
                    b.Property<int>("RechargeId")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RechargeId"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("RechargePlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RechargePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RechargeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RechargeId");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("Recharge", (string)null);
=======
                    b.ToTable("Recharge");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("Recharge");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<int>("AddonId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("Review", (string)null);
=======
                    b.ToTable("Review");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("Review");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });

            modelBuilder.Entity("dotnetapp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<< HEAD
<<<<<<< HEAD
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                        .HasColumnType("int")
                        .UseIdentityColumn();
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<< HEAD
<<<<<<< HEAD
                    b.ToTable("users", (string)null);
=======
                    b.ToTable("users");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
=======
                    b.ToTable("users");
>>>>>>> c0dea137e879487d0ce944b45ac10cf0d121c3de
                });
#pragma warning restore 612, 618
        }
    }
}
